steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "autoformat"

  - wait

  - label: "test redirection Lambda"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: edge_lambda
          command: ["yarn", "test"]

  - wait

  - label: "upload redirection Lambda to S3"
    branches: "main"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: edge_lambda
          command: ["yarn", "uploadToS3"]
