steps:
  - label: "Wellcome Library STAGE Redirects"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: edge_lambda
          command: ["yarn", "testRedirectsStage"]
    retry:
      automatic: true

  - label: "Wellcome Library PROD Redirects"
    plugins:
      - ecr#v2.1.1:
          login: true
      - docker-compose#v3.5.0:
          run: edge_lambda
          command: ["yarn", "testRedirects"]
    retry:
      automatic: true
